### ISSUE TITLE
Unhandled Runtime Error - TypeError: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by Marx-wrld** [Marx-wrld/Job-Description-Generator-using-ChatGPT-API#11]
src\components\Dashboard.js (46:42) @ trim

  44 |   setIsGenerating(false); //setting the isGenerating state back to false then converting the response to JSON format and setting it to the jobDescription state
  45 |   const data = await res.json();
> 46 |   setJobDescription(data.jobDescription.trim());
     |                                        ^
  47 | };
  48 | 
  49 | return (

**Comment by lelouchB** [comment]
@Marx-wrld 
You misspelt the API Key - OPEN_AI_KEY

Also, do not commit private keys to public GitHub repos or any repos. Its not secure.

**Comment by Marx-wrld** [comment]
resolved by renaming from OPEN_AI_KEY in .env file to OPENAI_API_KEY
